package colorscales

import (
	"image/color"
)

// ColorScale is interface for extracting color from float
type ColorScale interface {
	GetColor(val float64) color.RGBA
}

// LoadColorScale loads colorscale struct based on associated string name
func LoadColorScale(name string) ColorScale {
	switch name {
	case "PuBu9":
		return PuBu9
	case "GnBu9":
		return GnBu9
	case "YlGn9":
		return YlGn9
	case "Aquamarine":
		return Aquamarine
	case "Thermal":
		return Thermal
	case "alpine":
		return alpine
	case "aquamarine":
		return aquamarine
	case "army":
		return army
	case "atlantic":
		return atlantic
	case "auerbach":
		return auerbach
	case "aurora":
		return aurora
	case "autumn":
		return autumn
	case "avocado":
		return avocado
	case "beach":
		return beach
	case "blackbody":
		return blackbody
	case "bluegreenyellow":
		return bluegreenyellow
	case "bosch_garden":
		return bosch_garden
	case "bosch_hell":
		return bosch_hell
	case "botticelli":
		return botticelli
	case "brass":
		return brass
	case "browncyan":
		return browncyan
	case "canaletto":
		return canaletto
	case "candy":
		return candy
	case "cezanne":
		return cezanne
	case "cherry":
		return cherry
	case "cmyk":
		return cmyk
	case "coffee":
		return coffee
	case "cubehelix":
		return cubehelix
	case "darkrainbow":
		return darkrainbow
	case "darkterrain":
		return darkterrain
	case "deepsea":
		return deepsea
	case "fall":
		return fall
	case "fruitpunch":
		return fruitpunch
	case "fuchsia":
		return fuchsia
	case "grays1":
		return grays1
	case "grayyellow":
		return grayyellow
	case "greenbrownterrain":
		return greenbrownterrain
	case "greenpink":
		return greenpink
	case "hokusai":
		return hokusai
	case "holbein":
		return holbein
	case "island":
		return island
	case "jet":
		return jet
	case "klimt":
		return klimt
	case "lake":
		return lake
	case "leonardo":
		return leonardo
	case "lighttemperaturemap":
		return lighttemperaturemap
	case "lightterrain":
		return lightterrain
	case "mint":
		return mint
	case "munch":
		return munch
	case "neon":
		return neon
	case "pastel":
		return pastel
	case "pearl":
		return pearl
	case "picasso":
		return picasso
	case "pigeon":
		return pigeon
	case "plum":
		return plum
	case "rainbow":
		return rainbow
	case "redblue":
		return redblue
	case "redgreensplit":
		return redgreensplit
	case "rembrandt":
		return rembrandt
	case "rose":
		return rose
	case "rust":
		return rust
	case "sandyterrain":
		return sandyterrain
	case "sienna":
		return sienna
	case "sun":
		return sun
	case "southwest":
		return southwest
	case "starrynight":
		return starrynight
	case "sunset":
		return sunset
	case "temperaturemap":
		return temperaturemap
	case "thermometer":
		return thermometer
	case "valentine":
		return valentine
	case "vangogh":
		return vangogh
	case "vermeer":
		return vermeer
	case "watermelon":
		return watermelon
	case "CMRmap":
		return CMRmap
	case "julia_colorscheme":
		return julia_colorscheme
	case "turbo":
		return turbo
	case "algae":
		return algae
	case "amp":
		return amp
	case "balance":
		return balance
	case "curl":
		return curl
	case "deep":
		return deep
	case "delta":
		return delta
	case "dense":
		return dense
	case "grays":
		return grays
	case "haline":
		return haline
	case "ice":
		return ice
	case "matter":
		return matter
	case "oxy":
		return oxy
	case "phase":
		return phase
	case "solar":
		return solar
	case "speed":
		return speed
	case "tempo":
		return tempo
	case "thermal":
		return thermal
	case "turbid":
		return turbid
	case "PuRd_3":
		return PuRd_3
	case "PuRd_4":
		return PuRd_4
	case "PuRd_5":
		return PuRd_5
	case "PuRd_6":
		return PuRd_6
	case "PuRd_7":
		return PuRd_7
	case "PuRd_8":
		return PuRd_8
	case "PuRd_9":
		return PuRd_9
	case "Purples_3":
		return Purples_3
	case "Purples_4":
		return Purples_4
	case "Purples_5":
		return Purples_5
	case "Purples_6":
		return Purples_6
	case "Purples_7":
		return Purples_7
	case "Purples_8":
		return Purples_8
	case "Purples_9":
		return Purples_9
	case "Set1_3":
		return Set1_3
	case "Set1_4":
		return Set1_4
	case "Set1_5":
		return Set1_5
	case "Set1_6":
		return Set1_6
	case "Set1_7":
		return Set1_7
	case "Set1_8":
		return Set1_8
	case "Set1_9":
		return Set1_9
	case "Greens_3":
		return Greens_3
	case "Greens_4":
		return Greens_4
	case "Greens_5":
		return Greens_5
	case "Greens_6":
		return Greens_6
	case "Greens_7":
		return Greens_7
	case "Greens_8":
		return Greens_8
	case "Greens_9":
		return Greens_9
	case "YlOrRd_3":
		return YlOrRd_3
	case "YlOrRd_4":
		return YlOrRd_4
	case "YlOrRd_5":
		return YlOrRd_5
	case "YlOrRd_6":
		return YlOrRd_6
	case "YlOrRd_7":
		return YlOrRd_7
	case "YlOrRd_8":
		return YlOrRd_8
	case "YlOrRd_9":
		return YlOrRd_9
	case "Pastel1_3":
		return Pastel1_3
	case "Pastel1_4":
		return Pastel1_4
	case "Pastel1_5":
		return Pastel1_5
	case "Pastel1_6":
		return Pastel1_6
	case "Pastel1_7":
		return Pastel1_7
	case "Pastel1_8":
		return Pastel1_8
	case "Pastel1_9":
		return Pastel1_9
	case "RdYlBu_3":
		return RdYlBu_3
	case "RdYlBu_4":
		return RdYlBu_4
	case "RdYlBu_5":
		return RdYlBu_5
	case "RdYlBu_6":
		return RdYlBu_6
	case "RdYlBu_7":
		return RdYlBu_7
	case "RdYlBu_8":
		return RdYlBu_8
	case "RdYlBu_9":
		return RdYlBu_9
	case "RdYlBu_10":
		return RdYlBu_10
	case "RdYlBu_11":
		return RdYlBu_11
	case "YlGnBu_3":
		return YlGnBu_3
	case "YlGnBu_4":
		return YlGnBu_4
	case "YlGnBu_5":
		return YlGnBu_5
	case "YlGnBu_6":
		return YlGnBu_6
	case "YlGnBu_7":
		return YlGnBu_7
	case "YlGnBu_8":
		return YlGnBu_8
	case "YlGnBu_9":
		return YlGnBu_9
	case "Blues_3":
		return Blues_3
	case "Blues_4":
		return Blues_4
	case "Blues_5":
		return Blues_5
	case "Blues_6":
		return Blues_6
	case "Blues_7":
		return Blues_7
	case "Blues_8":
		return Blues_8
	case "Blues_9":
		return Blues_9
	case "Set3_3":
		return Set3_3
	case "Set3_4":
		return Set3_4
	case "Set3_5":
		return Set3_5
	case "Set3_6":
		return Set3_6
	case "Set3_7":
		return Set3_7
	case "Set3_8":
		return Set3_8
	case "Set3_9":
		return Set3_9
	case "Set3_10":
		return Set3_10
	case "Set3_11":
		return Set3_11
	case "Set3_12":
		return Set3_12
	case "Reds_3":
		return Reds_3
	case "Reds_4":
		return Reds_4
	case "Reds_5":
		return Reds_5
	case "Reds_6":
		return Reds_6
	case "Reds_7":
		return Reds_7
	case "Reds_8":
		return Reds_8
	case "Reds_9":
		return Reds_9
	case "PuBu_3":
		return PuBu_3
	case "PuBu_4":
		return PuBu_4
	case "PuBu_5":
		return PuBu_5
	case "PuBu_6":
		return PuBu_6
	case "PuBu_7":
		return PuBu_7
	case "PuBu_8":
		return PuBu_8
	case "PuBu_9":
		return PuBu_9
	case "BuPu_3":
		return BuPu_3
	case "BuPu_4":
		return BuPu_4
	case "BuPu_5":
		return BuPu_5
	case "BuPu_6":
		return BuPu_6
	case "BuPu_7":
		return BuPu_7
	case "BuPu_8":
		return BuPu_8
	case "BuPu_9":
		return BuPu_9
	case "RdYlGn_3":
		return RdYlGn_3
	case "RdYlGn_4":
		return RdYlGn_4
	case "RdYlGn_5":
		return RdYlGn_5
	case "RdYlGn_6":
		return RdYlGn_6
	case "RdYlGn_7":
		return RdYlGn_7
	case "RdYlGn_8":
		return RdYlGn_8
	case "RdYlGn_9":
		return RdYlGn_9
	case "RdYlGn_10":
		return RdYlGn_10
	case "RdYlGn_11":
		return RdYlGn_11
	case "Pastel2_3":
		return Pastel2_3
	case "Pastel2_4":
		return Pastel2_4
	case "Pastel2_5":
		return Pastel2_5
	case "Pastel2_6":
		return Pastel2_6
	case "Pastel2_7":
		return Pastel2_7
	case "Pastel2_8":
		return Pastel2_8
	case "BuGn_3":
		return BuGn_3
	case "BuGn_4":
		return BuGn_4
	case "BuGn_5":
		return BuGn_5
	case "BuGn_6":
		return BuGn_6
	case "BuGn_7":
		return BuGn_7
	case "BuGn_8":
		return BuGn_8
	case "BuGn_9":
		return BuGn_9
	case "YlOrBr_3":
		return YlOrBr_3
	case "YlOrBr_4":
		return YlOrBr_4
	case "YlOrBr_5":
		return YlOrBr_5
	case "YlOrBr_6":
		return YlOrBr_6
	case "YlOrBr_7":
		return YlOrBr_7
	case "YlOrBr_8":
		return YlOrBr_8
	case "YlOrBr_9":
		return YlOrBr_9
	case "PuBuGn_3":
		return PuBuGn_3
	case "PuBuGn_4":
		return PuBuGn_4
	case "PuBuGn_5":
		return PuBuGn_5
	case "PuBuGn_6":
		return PuBuGn_6
	case "PuBuGn_7":
		return PuBuGn_7
	case "PuBuGn_8":
		return PuBuGn_8
	case "PuBuGn_9":
		return PuBuGn_9
	case "Spectral_3":
		return Spectral_3
	case "Spectral_4":
		return Spectral_4
	case "Spectral_5":
		return Spectral_5
	case "Spectral_6":
		return Spectral_6
	case "Spectral_7":
		return Spectral_7
	case "Spectral_8":
		return Spectral_8
	case "Spectral_9":
		return Spectral_9
	case "Spectral_10":
		return Spectral_10
	case "Spectral_11":
		return Spectral_11
	case "YlGn_3":
		return YlGn_3
	case "YlGn_4":
		return YlGn_4
	case "YlGn_5":
		return YlGn_5
	case "YlGn_6":
		return YlGn_6
	case "YlGn_7":
		return YlGn_7
	case "YlGn_8":
		return YlGn_8
	case "YlGn_9":
		return YlGn_9
	case "RdGy_3":
		return RdGy_3
	case "RdGy_4":
		return RdGy_4
	case "RdGy_5":
		return RdGy_5
	case "RdGy_6":
		return RdGy_6
	case "RdGy_7":
		return RdGy_7
	case "RdGy_8":
		return RdGy_8
	case "RdGy_9":
		return RdGy_9
	case "RdGy_10":
		return RdGy_10
	case "RdGy_11":
		return RdGy_11
	case "Greys_3":
		return Greys_3
	case "Greys_4":
		return Greys_4
	case "Greys_5":
		return Greys_5
	case "Greys_6":
		return Greys_6
	case "Greys_7":
		return Greys_7
	case "Greys_8":
		return Greys_8
	case "Greys_9":
		return Greys_9
	case "BrBG_3":
		return BrBG_3
	case "BrBG_4":
		return BrBG_4
	case "BrBG_5":
		return BrBG_5
	case "BrBG_6":
		return BrBG_6
	case "BrBG_7":
		return BrBG_7
	case "BrBG_8":
		return BrBG_8
	case "BrBG_9":
		return BrBG_9
	case "BrBG_10":
		return BrBG_10
	case "BrBG_11":
		return BrBG_11
	case "RdPu_3":
		return RdPu_3
	case "RdPu_4":
		return RdPu_4
	case "RdPu_5":
		return RdPu_5
	case "RdPu_6":
		return RdPu_6
	case "RdPu_7":
		return RdPu_7
	case "RdPu_8":
		return RdPu_8
	case "RdPu_9":
		return RdPu_9
	case "PRGn_3":
		return PRGn_3
	case "PRGn_4":
		return PRGn_4
	case "PRGn_5":
		return PRGn_5
	case "PRGn_6":
		return PRGn_6
	case "PRGn_7":
		return PRGn_7
	case "PRGn_8":
		return PRGn_8
	case "PRGn_9":
		return PRGn_9
	case "PRGn_10":
		return PRGn_10
	case "PRGn_11":
		return PRGn_11
	case "Dark2_3":
		return Dark2_3
	case "Dark2_4":
		return Dark2_4
	case "Dark2_5":
		return Dark2_5
	case "Dark2_6":
		return Dark2_6
	case "Dark2_7":
		return Dark2_7
	case "Dark2_8":
		return Dark2_8
	case "RdBu_3":
		return RdBu_3
	case "RdBu_4":
		return RdBu_4
	case "RdBu_5":
		return RdBu_5
	case "RdBu_6":
		return RdBu_6
	case "RdBu_7":
		return RdBu_7
	case "RdBu_8":
		return RdBu_8
	case "RdBu_9":
		return RdBu_9
	case "RdBu_10":
		return RdBu_10
	case "RdBu_11":
		return RdBu_11
	case "PuOr_3":
		return PuOr_3
	case "PuOr_4":
		return PuOr_4
	case "PuOr_5":
		return PuOr_5
	case "PuOr_6":
		return PuOr_6
	case "PuOr_7":
		return PuOr_7
	case "PuOr_8":
		return PuOr_8
	case "PuOr_9":
		return PuOr_9
	case "PuOr_10":
		return PuOr_10
	case "PuOr_11":
		return PuOr_11
	case "Paired_3":
		return Paired_3
	case "Paired_4":
		return Paired_4
	case "Paired_5":
		return Paired_5
	case "Paired_6":
		return Paired_6
	case "Paired_7":
		return Paired_7
	case "Paired_8":
		return Paired_8
	case "Paired_9":
		return Paired_9
	case "Paired_10":
		return Paired_10
	case "Paired_11":
		return Paired_11
	case "Paired_12":
		return Paired_12
	case "Set2_3":
		return Set2_3
	case "Set2_4":
		return Set2_4
	case "Set2_5":
		return Set2_5
	case "Set2_6":
		return Set2_6
	case "Set2_7":
		return Set2_7
	case "Set2_8":
		return Set2_8
	case "Oranges_3":
		return Oranges_3
	case "Oranges_4":
		return Oranges_4
	case "Oranges_5":
		return Oranges_5
	case "Oranges_6":
		return Oranges_6
	case "Oranges_7":
		return Oranges_7
	case "Oranges_8":
		return Oranges_8
	case "Oranges_9":
		return Oranges_9
	case "OrRd_3":
		return OrRd_3
	case "OrRd_4":
		return OrRd_4
	case "OrRd_5":
		return OrRd_5
	case "OrRd_6":
		return OrRd_6
	case "OrRd_7":
		return OrRd_7
	case "OrRd_8":
		return OrRd_8
	case "OrRd_9":
		return OrRd_9
	case "Accent_3":
		return Accent_3
	case "Accent_4":
		return Accent_4
	case "Accent_5":
		return Accent_5
	case "Accent_6":
		return Accent_6
	case "Accent_7":
		return Accent_7
	case "Accent_8":
		return Accent_8
	case "GnBu_3":
		return GnBu_3
	case "GnBu_4":
		return GnBu_4
	case "GnBu_5":
		return GnBu_5
	case "GnBu_6":
		return GnBu_6
	case "GnBu_7":
		return GnBu_7
	case "GnBu_8":
		return GnBu_8
	case "GnBu_9":
		return GnBu_9
	case "PiYG_3":
		return PiYG_3
	case "PiYG_4":
		return PiYG_4
	case "PiYG_5":
		return PiYG_5
	case "PiYG_6":
		return PiYG_6
	case "PiYG_7":
		return PiYG_7
	case "PiYG_8":
		return PiYG_8
	case "PiYG_9":
		return PiYG_9
	case "PiYG_10":
		return PiYG_10
	case "PiYG_11":
		return PiYG_11
	case "cyclic_grey_15_85_c0_n256":
		return cyclic_grey_15_85_c0_n256
	case "cyclic_grey_15_85_c0_n256_s25":
		return cyclic_grey_15_85_c0_n256_s25
	case "cyclic_mrybm_35_75_c68_n256":
		return cyclic_mrybm_35_75_c68_n256
	case "cyclic_mrybm_35_75_c68_n256_s25":
		return cyclic_mrybm_35_75_c68_n256_s25
	case "cyclic_mygbm_30_95_c78_n256":
		return cyclic_mygbm_30_95_c78_n256
	case "cyclic_mygbm_30_95_c78_n256_s25":
		return cyclic_mygbm_30_95_c78_n256_s25
	case "cyclic_wrwbw_40_90_c42_n256":
		return cyclic_wrwbw_40_90_c42_n256
	case "cyclic_wrwbw_40_90_c42_n256_s25":
		return cyclic_wrwbw_40_90_c42_n256_s25
	case "diverging_isoluminant_cjm_75_c23_n256":
		return diverging_isoluminant_cjm_75_c23_n256
	case "diverging_isoluminant_cjm_75_c24_n256":
		return diverging_isoluminant_cjm_75_c24_n256
	case "diverging_isoluminant_cjo_70_c25_n256":
		return diverging_isoluminant_cjo_70_c25_n256
	case "diverging_linear_bjr_30_55_c53_n256":
		return diverging_linear_bjr_30_55_c53_n256
	case "diverging_linear_bjy_30_90_c45_n256":
		return diverging_linear_bjy_30_90_c45_n256
	case "diverging_rainbow_bgymr_45_85_c67_n256":
		return diverging_rainbow_bgymr_45_85_c67_n256
	case "diverging_bkr_55_10_c35_n256":
		return diverging_bkr_55_10_c35_n256
	case "diverging_bky_60_10_c30_n256":
		return diverging_bky_60_10_c30_n256
	case "diverging_bwr_40_95_c42_n256":
		return diverging_bwr_40_95_c42_n256
	case "diverging_bwr_55_98_c37_n256":
		return diverging_bwr_55_98_c37_n256
	case "diverging_cwm_80_100_c22_n256":
		return diverging_cwm_80_100_c22_n256
	case "diverging_gkr_60_10_c40_n256":
		return diverging_gkr_60_10_c40_n256
	case "diverging_gwr_55_95_c38_n256":
		return diverging_gwr_55_95_c38_n256
	case "diverging_gwv_55_95_c39_n256":
		return diverging_gwv_55_95_c39_n256
	case "isoluminant_cgo_70_c39_n256":
		return isoluminant_cgo_70_c39_n256
	case "isoluminant_cgo_80_c38_n256":
		return isoluminant_cgo_80_c38_n256
	case "isoluminant_cm_70_c39_n256":
		return isoluminant_cm_70_c39_n256
	case "linear_bgy_10_95_c74_n256":
		return linear_bgy_10_95_c74_n256
	case "linear_bgyw_15_100_c67_n256":
		return linear_bgyw_15_100_c67_n256
	case "linear_bgyw_15_100_c68_n256":
		return linear_bgyw_15_100_c68_n256
	case "linear_blue_5_95_c73_n256":
		return linear_blue_5_95_c73_n256
	case "linear_blue_95_50_c20_n256":
		return linear_blue_95_50_c20_n256
	case "linear_bmw_5_95_c86_n256":
		return linear_bmw_5_95_c86_n256
	case "linear_bmw_5_95_c89_n256":
		return linear_bmw_5_95_c89_n256
	case "linear_bmy_10_95_c71_n256":
		return linear_bmy_10_95_c71_n256
	case "linear_bmy_10_95_c78_n256":
		return linear_bmy_10_95_c78_n256
	case "linear_gow_60_85_c27_n256":
		return linear_gow_60_85_c27_n256
	case "linear_gow_65_90_c35_n256":
		return linear_gow_65_90_c35_n256
	case "linear_green_5_95_c69_n256":
		return linear_green_5_95_c69_n256
	case "linear_grey_0_100_c0_n256":
		return linear_grey_0_100_c0_n256
	case "linear_grey_10_95_c0_n256":
		return linear_grey_10_95_c0_n256
	case "linear_kry_5_95_c72_n256":
		return linear_kry_5_95_c72_n256
	case "linear_kry_5_98_c75_n256":
		return linear_kry_5_98_c75_n256
	case "linear_kryw_0_100_c71_n256":
		return linear_kryw_0_100_c71_n256
	case "linear_kryw_5_100_c64_n256":
		return linear_kryw_5_100_c64_n256
	case "linear_kryw_5_100_c67_n256":
		return linear_kryw_5_100_c67_n256
	case "linear_ternary_blue_0_44_c57_n256":
		return linear_ternary_blue_0_44_c57_n256
	case "linear_ternary_green_0_46_c42_n256":
		return linear_ternary_green_0_46_c42_n256
	case "linear_ternary_red_0_50_c52_n256":
		return linear_ternary_red_0_50_c52_n256
	case "rainbow_bgyr_35_85_c72_n256":
		return rainbow_bgyr_35_85_c72_n256
	case "rainbow_bgyr_35_85_c73_n256":
		return rainbow_bgyr_35_85_c73_n256
	case "rainbow_bgyrm_35_85_c69_n256":
		return rainbow_bgyrm_35_85_c69_n256
	case "rainbow_bgyrm_35_85_c71_n256":
		return rainbow_bgyrm_35_85_c71_n256
	case "tol_bright":
		return tol_bright
	case "tol_muted":
		return tol_muted
	case "tol_light":
		return tol_light
	case "okabe_ito":
		return okabe_ito
	case "mk_8":
		return mk_8
	case "mk_12":
		return mk_12
	case "mk_15":
		return mk_15
	case "rainbow1":
		return rainbow1
	case "gnuplot":
		return gnuplot
	case "gnuplot2":
		return gnuplot2
	case "ocean":
		return ocean
	case "afmhot":
		return afmhot
	case "rainbow2":
		return rainbow2
	case "prism":
		return prism
	case "flag":
		return flag
	case "brg":
		return brg
	case "bwr":
		return bwr
	case "coolwarm":
		return coolwarm
	case "gist_heat":
		return gist_heat
	case "gist_yarg":
		return gist_yarg
	case "gist_gray":
		return gist_gray
	case "magma":
		return magma
	case "inferno":
		return inferno
	case "plasma":
		return plasma
	case "viridis":
		return viridis
	case "twilight":
		return twilight
	case "bone":
		return bone
	case "binary":
		return binary
	case "autumn1":
		return autumn1
	case "bone_1":
		return bone_1
	case "cool":
		return cool
	case "copper":
		return copper
	case "gray1":
		return gray1
	case "hot":
		return hot
	case "hsv":
		return hsv
	case "jet1":
		return jet1
	case "pink":
		return pink
	case "spring":
		return spring
	case "summer":
		return summer
	case "winter":
		return winter
	case "nipy_spectral":
		return nipy_spectral
	case "gist_earth":
		return gist_earth
	case "gist_ncar":
		return gist_ncar
	case "gist_stern":
		return gist_stern
	case "gist_rainbow":
		return gist_rainbow
	case "seismic":
		return seismic
	case "terrain":
		return terrain
	case "tab10":
		return tab10
	case "tab20":
		return tab20
	case "tab20b":
		return tab20b
	case "tab20c":
		return tab20c
	case "Wistia":
		return Wistia
	case "acton":
		return acton
	case "bamako":
		return bamako
	case "batlow":
		return batlow
	case "berlin":
		return berlin
	case "bilbao":
		return bilbao
	case "broc":
		return broc
	case "brocO":
		return brocO
	case "buda":
		return buda
	case "cork":
		return cork
	case "corkO":
		return corkO
	case "davos":
		return davos
	case "devon":
		return devon
	case "grayC":
		return grayC
	case "hawaii":
		return hawaii
	case "imola":
		return imola
	case "lajolla":
		return lajolla
	case "lapaz":
		return lapaz
	case "lisbon":
		return lisbon
	case "nuuk":
		return nuuk
	case "oleron":
		return oleron
	case "oslo":
		return oslo
	case "roma":
		return roma
	case "romaO":
		return romaO
	case "tofino":
		return tofino
	case "tokyo":
		return tokyo
	case "turku":
		return turku
	case "vik":
		return vik
	case "vikO":
		return vikO
	case "seaborn_bright":
		return seaborn_bright
	case "seaborn_bright6":
		return seaborn_bright6
	case "seaborn_deep":
		return seaborn_deep
	case "seaborn_deep6":
		return seaborn_deep6
	case "seaborn_dark":
		return seaborn_dark
	case "seaborn_dark6":
		return seaborn_dark6
	case "seaborn_colorblind":
		return seaborn_colorblind
	case "seaborn_colorblind6":
		return seaborn_colorblind6
	case "seaborn_muted":
		return seaborn_muted
	case "seaborn_muted6":
		return seaborn_muted6
	case "seaborn_pastel":
		return seaborn_pastel
	case "seaborn_pastel6":
		return seaborn_pastel6
	case "seaborn_rocket_gradient":
		return seaborn_rocket_gradient
	case "seaborn_icefire_gradient":
		return seaborn_icefire_gradient
	case "tableau_10":
		return tableau_10
	case "tableau_20":
		return tableau_20
	case "tableau_colorblind":
		return tableau_colorblind
	case "tableau_seattle_grays":
		return tableau_seattle_grays
	case "tableau_traffic":
		return tableau_traffic
	case "tableau_miller_stone":
		return tableau_miller_stone
	case "tableau_superfishel_stone":
		return tableau_superfishel_stone
	case "tableau_nuriel_stone":
		return tableau_nuriel_stone
	case "tableau_jewel_bright":
		return tableau_jewel_bright
	case "tableau_summer":
		return tableau_summer
	case "tableau_winter":
		return tableau_winter
	case "tableau_green_orange_teal":
		return tableau_green_orange_teal
	case "tableau_red_blue_brown":
		return tableau_red_blue_brown
	case "tableau_purple_pink_gray":
		return tableau_purple_pink_gray
	case "tableau_hue_circle":
		return tableau_hue_circle
	case "tableau_orange_blue":
		return tableau_orange_blue
	case "tableau_red_green":
		return tableau_red_green
	case "tableau_green_blue":
		return tableau_green_blue
	case "tableau_red_blue":
		return tableau_red_blue
	case "tableau_red_black":
		return tableau_red_black
	case "tableau_gold_purple":
		return tableau_gold_purple
	case "tableau_red_green_gold":
		return tableau_red_green_gold
	case "tableau_sunset_sunrise":
		return tableau_sunset_sunrise
	case "tableau_orange_blue_white":
		return tableau_orange_blue_white
	case "tableau_red_green_white":
		return tableau_red_green_white
	case "tableau_green_blue_white":
		return tableau_green_blue_white
	case "tableau_red_blue_white":
		return tableau_red_blue_white
	case "tableau_red_lack_white":
		return tableau_red_lack_white
	case "tableau_orang_blue_light":
		return tableau_orang_blue_light
	case "tableau_temperature":
		return tableau_temperature
	case "tableau_blue_green":
		return tableau_blue_green
	case "tableau_blue_light":
		return tableau_blue_light
	case "tableau_orange_light":
		return tableau_orange_light
	default:
		panic("Unknown colorscale: " + name)
	}
}
